### ISSUE TITLE
tensorflow/core/lib/strings/numbers.cc:26:10: fatal error: 'double-conversion/double-conversion.h' file not found

### ISSUE THREAD

**Issue by anonym24** [JieHe96/iOS_Tensorflow_ObjectDetection_Example#21]
Quick Start

2.Compile dependencies

Compile ios dependencies:

```
cd $TF_ROOT
tensorflow/contrib/makefile/build_all_ios_ssd.sh
```

```
tensorflow/core/lib/strings/numbers.cc:26:10: fatal error: 
      'double-conversion/double-conversion.h' file not found
#include "double-conversion/double-conversion.h"
         ^
1 error generated.
make: *** [/Users/admin/tensorflow-master/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/strings/numbers.o] Error 1
make: *** Waiting for unfinished jobs....
+ '[' 2 -ne 0 ']'
+ echo 'arm64 compilation failed.'
arm64 compilation failed.
+ exit 1
```

**Comment by anonym24** [comment]
I'll try `brew install double-conversion` and answer later if it helped me

**Comment by anonym24** [comment]
I guess I should not get those errors at all because script downloads needed dependencies itself:

I have next 

```
Mac-Admin:downloads admin$ ls -d "$PWD"/*
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/absl
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/double_conversion
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/eigen
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/fft2d
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/gemmlowp
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/googletest
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/nsync
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf
/users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/re2
```

but still why it does not use them? or mb problem in MAC OSX?

already installed `protobuf `&& `double_conversion` using `homebrew (brew)`, also `wget` (because script build_all_ios_ssd.sh downloads files using wget)

so after 

`brew install double-conversion`

now I get this error:

```
tensorflow/core/lib/strings/numbers.cc:43:55: error: no member named
      'ALLOW_CASE_INSENSIBILITY' in 'double_conversion::StringToDoubleConverter'
        | double_conversion::StringToDoubleConverter::ALLOW_CASE_INSENSIBILITY,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
make: *** [/Users/admin/tensorflow-master/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/strings/numbers.o] Error 1
make: *** Waiting for unfinished jobs....
+ '[' 2 -ne 0 ']'
+ echo 'arm64 compilation failed.'
arm64 compilation failed.
+ exit 1

```

**Comment by madhavajay** [comment]
I managed to get it to compile with TensorFlow tag 1.4.0 on OSX Sierra. I just installed the dependencies like bazel and autoconf etc using Brew and everything worked fine.

**Comment by anonym24** [comment]
solved

thanks to @madhavajay
